### ISSUE TITLE
Пустая вкладка Database

### ISSUE THREAD

**Issue by blink2004** [zhuravljov/yii2-debug#39]
в конфигах прописал
        'enableProfiling' => true,
        'enableParamLogging' => true,
но при открытии вкладки database она пустует.

**Comment by zhuravljov** [comment]
А что на вкладке "Profiling"?

**Comment by adeg** [comment]
У меня та же проблема.

Во вкладках Database, Profiling и Database не отображается информация. Вкладки Request и Configuration работают. Проблема появилась после апгрейда на Yii 1.1.16.

**Comment by kilinvs** [comment]
Была такая проблема, копать в сторону логгера.
Был CLogRouter, стал CSysLogRoute.

**Comment by zhuravljov** [comment]
У меня нет под руками проекта с 1.1.16.
Что отладчик пишет в логи? Панели Database и Profiling что-то сохраняют?

Посмотреть можно с помощью кода:
```php
$data = unserialize(file_get_contents('.../runtime/54aae46a52a49.data'));
var_export($data['db']);
var_export($data['profiling']);
```

**Comment by adeg** [comment]
Поломалось скорее всего вот почему:
CLogger срабатывает по событию onEndRequest и при завершении удаляет все логи. Компонент Yii2Debug также срабатывал по onEndRequest, считывая те же логи, которые читает CLogger. Но теперь когда срабатывает Yii2Debug в памяти уже пусто. Я так понимаю, что нужно интегрировать Yii2Debug с CLogger-ом, чтобы он становился одним из route CLogger-а?

**Comment by zhuravljov** [comment]
@adeg, да, похоже так и есть.
Варианты решения: или делать свой роут для логгера, или подписаться на `CLogger::onFlush`.

**Comment by blink2004** [comment]
Во вкладках Database, Profiling и Database не отображается информация. Вкладки Request и Configuration работают.
Аналогично, но еще на 1.1.15. Вроде права везде 777.

**Comment by adeg** [comment]
@blink2004, скорее всего у вас framework/logging/CLogRouter.php в версии от 20 июня. Релиз 1.1.15 был 29.06.2014, но не включал в себя https://github.com/yiisoft/yii/commit/2d10f419c1a1b4eb48500083bf63f6287330fb14 от 20.06.2014. Возможно, фреймворк был скачан git-ом из ветки master?

До реализации кем-нибудь решения, предложенного @zhuravljov, могу посоветовать workaround: использовать [framework/logging/CLogRouter.php от 15.01.2013](https://github.com/yiisoft/yii/blob/6247adaf26df41d60c09a6d18e6f508b69cc0efd/framework/logging/CLogRouter.php).

**Comment by kikimor** [comment]
Вариант решения проблемы с созданием своего CLogRoute: #42

**Comment by blink2004** [comment]
Обновил файлы из репозитория https://github.com/zhuravljov/yii2-debug и CLogRouter. Заработало :)
