### ISSUE TITLE
Сделать открытите дебаггера как popup-окно

### ISSUE THREAD

**Issue by blink2004** [zhuravljov/yii2-debug#40]
Можно сделать, чтобы при нажатии на панель она разворачивалась на высоту всего экрана, а затем при событии сворачивалась обратно. Не удобно каждый раз перезагружать страницу. Спасибо.

**Comment by zhuravljov** [comment]
Зачем? Модуль логичнее открывать в отдельной вкладке, и смотреть детальную отладочную информацию там.

**Comment by blink2004** [comment]
Тоже вариант.
