### ISSUE TITLE
Панель не отображается на некоторых страницах

### ISSUE THREAD

**Issue by blink2004** [zhuravljov/yii2-debug#41]
Пенель почему-то отображается на одних страницах, а на других и вовсе её нет.

**Comment by zhuravljov** [comment]
Нужно больше информации.

1. Панель подгружается через ajax. Что говорит фаербаг?
2. Корректно ли завершается yii-процесс?
3. Нет ли где-нибудь `exit()`, или чего-то подобного?

**Comment by blink2004** [comment]
1. Да ничего вроде. Смотрю через Chrome, на вкладке консоли - пусто.
2. Вроде тоже да. Как проверить? Т.к. сама страница загружается
3. Местами есть Yii::app()->end(); где используется AJAX.
