### ISSUE TITLE
Не удаляются старые логи

### ISSUE THREAD

**Issue by Godnob** [zhuravljov/yii2-debug#45]
В настройках указал
'historySize' => 1000
но файлов в папке debug/ скопилось уже 200 000

**Comment by zhuravljov** [comment]
За удаление старых отвечает эта точка в коде
https://github.com/zhuravljov/yii2-debug/blob/master/Yii2Debug.php#L274
Попробуйте убрать `@` чтобы отследить ошибку.

Возможно что-то с правами на уровне файловой системы.

**Comment by kilinvs** [comment]
при большой нагрузке параллельные процессы перезатирают index файл, отсюда появляются логи неучтенные в индексе, поэтому и не происходит удаление

**Comment by zhuravljov** [comment]
@kilinvs если включать модуль на боевом?

**Comment by kilinvs** [comment]
@zhuravljov да, думаю тут дело именно в этом

**Comment by zhuravljov** [comment]
В Yii2 сделали блокировку через flock():
https://github.com/yiisoft/yii2-debug/blob/master/LogTarget.php#L76
Перенесу решение сюда.

**Comment by Godnob** [comment]
@zhuravljov я нашел эту строку, добавил вывод данных в файл, там увидел что расхождения между index и data-файлами, как и сказал @kilinvs 
Обнаружил на боевом, когда пошли ошибки уже.

Последняя тема была тут год назад, не думал что ответят :)

**Comment by zhuravljov** [comment]
@Godnob вообще на боевом использовать дебаггер - не лучшее решение. Это достаточно громоздкая штука. В некоторых местах пересоздается контроллер с полным анализом роутов. Собирается большое кол-во информации, которая не нужна для продакшена в штатном режиме работы.

С ним удобно разрабатывать, а на боевом практичнее вести обычные логи.

> Последняя тема была тут год назад, не думал что ответят :)

Рискну предположить, что у всех все работает, и баги закончились ))
