### ISSUE TITLE
Unable to see SQL queries

### ISSUE THREAD

**Issue by senguttuvang** [zhuravljov/yii2-debug#47]
The database panel is always empty for me. I'm able to see data Logs panel. I'm sure I have enabled both debugging, trace level & db params to true, still that panel is empty. Any idea?

**Comment by zhuravljov** [comment]
To see database queries need to enable an options:

```php
return array(
    'components' => array(
        'db' => array(
            'enableProfiling' => true,
            'enableParamLogging' => true,
        ),
    ),
);
```

Read more in [readme.md](https://github.com/zhuravljov/yii2-debug/blob/master/README.md#installation).

**Comment by senguttuvang** [comment]
As I said in the issue, these statements are already there, still the panel is empty.

**Comment by zhuravljov** [comment]
Debug panel works in all my yii1 projects. I see all queries and other debug info.
Probably problem in your project code and I can't to help you, because I don't see that, sorry.
In first, try to check queries by LogRouter.

**Comment by zhuravljov** [comment]
Need more info about the issue.
