### ISSUE TITLE
кешированный SQL-запрос или нет?

### ISSUE THREAD

**Issue by maloknsi** [zhuravljov/yii2-debug#52]
Есть ли возможность просматривать кол-во кэшированных SQL запросов? 
Общее кол-во(время выполнение)/кол-во в кеше(время выполнения) ?
Подсветка кэшированного запроса SQL в "Database"

**Comment by zhuravljov** [comment]
А как вы это определите?
Кеш для того и нужен, чтобы запросы, не доходили до БД, где в этом есть необходимость. Тех запросов, где результат из кеша, в выборке не будет.
Сравнить кол-во запросов на страницу с кешем и без можно только включив и выключив его.

**Comment by maloknsi** [comment]
> Тех запросов, где результат из кеша, в выборке не будет.
>Сравнить кол-во запросов на страницу с кешем и без можно только включив и выключив его.

Точно, панель же закешировалась вместе со страницей и я перешел на старые логи отладки, которые формировались без кеша. 
Перешел на вкладку "All", выбрал последний лог - там были SQL, не вошедшие в кеш. 
Спасибо!
