### ISSUE TITLE
Фильтрация по времени выполнения SQL запросов в "Database"

### ISSUE THREAD

**Issue by maloknsi** [zhuravljov/yii2-debug#53]
Возможно ли добавить фильтрацию по времени выполнения SQL запросов в "Database"?
К примеру, "fast,medium,long" и вынести в конфиг или назначить время "до 1ms", "до 1s", "более 1s"

**Comment by zhuravljov** [comment]
В закладке "Resume" запросы отсортированы по времени выполнения.

**Comment by maloknsi** [comment]
точно, спасибо!
